name: SurvivalInvisiframes
version: ${project.version}
api-version: 1.16
main: com.darkender.plugins.survivalinvisiframes.SurvivalInvisiframes
author: Techdoodle
commands:
  iframe:
    permission: survivalinvisiframes.cmd
    description: Gives the player an invisible item frame
    usage: /iframe
permissions:
  survivalinvisiframes.place:
    default: true
  survivalinvisiframes.craft:
    default: true
  survivalinvisiframes.cmd:
    default: op
  survivalinvisiframes.reload:
    default: op
  survivalinvisiframes.forcerecheck:
    default: op
  survivalinvisiframes.get:
    default: op
  survivalinvisiframes.setitem:
    default: op
  survivalinvisiframes.give:
    default: op